# We will delete this file once these tests actually work in a CI environment

name: Temp Run Acceptance Tests

permissions:
  contents: write

on: [pull_request]

jobs:
  test:
    name: Run Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          cache: true
          go-version-file: 'go.mod'

      - name: Cache Go Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: |
          go mod download
          go mod tidy

      - name: Run Tests
        env:
          HCP_API_HOST: ${{ secrets.HCP_API_HOST }}
          HCP_AUTH_URL: ${{ secrets.HCP_AUTH_URL }}
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
        run: make testacc-ci

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Test Coverage
          path: coverage.html
